name: Trigger auto deployment for fcg-jogos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fcg-jogos-AutoDeployTrigger-2205f752-bae0-4bfd-880b-c64cfa2a8ad3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FCGJOGOS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FCGJOGOS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FCGJOGOS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.FCGJOGOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FCGJOGOS_REGISTRY_PASSWORD }}
          containerAppName: fcg-jogos
          resourceGroup: rg-functions
          imageToBuild: gabrielpaulino/fcg-jogos:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


